export const useres = [
    {
      id: 29,
      email: "george.bluth@reqres.in",
      first_name: "George",
      last_name: "Bluth",
      job: 'Programmer',
      avatar: "https://reqres.in/img/faces/1-image.jpg",
    },
    {
      id: 32,
      email: "janet.weaver@reqres.in",
      first_name: "Janet",
      last_name: "Weaver",
      job: 'Doctor',
      avatar: "https://reqres.in/img/faces/2-image.jpg",
    },
    {
      id: 23,
      email: "emma.wong@reqres.in",
      first_name: "Emma",
      last_name: "Wong",
      job: 'Manager',
      avatar: "https://reqres.in/img/faces/3-image.jpg",
    },
    {
      id: 49,
      email: "eve.holt@reqres.in",
      first_name: "Eve",
      last_name: "Holt",
      job: 'Engineer',
      avatar: "https://reqres.in/img/faces/4-image.jpg",
    },
    {
      id: 38,
      email: "charles.morris@reqres.in",
      first_name: "Charles",
      last_name: "Morris",
      job: 'Engineer',
      avatar: "https://reqres.in/img/faces/5-image.jpg",
    },
    {
      id: 36,
      email: "tracey.ramos@reqres.in",
      first_name: "Tracey",
      last_name: "Ramos",
      job: 'Programmer',
      avatar: "https://reqres.in/img/faces/6-image.jpg",
    },
    {
      id: 34,
      email: "michael.lawson@reqres.in",
      first_name: "Michael",
      last_name: "Lawson",
      job: 'Doctor',
      avatar: "https://reqres.in/img/faces/7-image.jpg",
    },
    {
      id: 28,
      email: "lindsay.ferguson@reqres.in",
      first_name: "Lindsay",
      last_name: "Ferguson",
      job: 'Programmer',
      avatar: "https://reqres.in/img/faces/8-image.jpg",
    },
    {
      id: 30,
      email: "tobias.funke@reqres.in",
      first_name: "Tobias",
      last_name: "Funke",
      job: 'Teacher',
      avatar: "https://reqres.in/img/faces/9-image.jpg",
    },
    {
      id: 33,
      email: "byron.fields@reqres.in",
      first_name: "Byron",
      last_name: "Fields",
      job: 'Engineer',
      avatar: "https://reqres.in/img/faces/10-image.jpg",
    },
    {
      id: 29,
      email: "george.edwards@reqres.in",
      first_name: "George",
      last_name: "Edwards",
      job: 'Teacher',
      avatar: "https://reqres.in/img/faces/11-image.jpg",
    },
    {
      id: 35,
      email: "rachel.howell@reqres.in",
      first_name: "Rachel",
      last_name: "Howell",
      job: 'Doctor',
      avatar: "https://reqres.in/img/faces/12-image.jpg",
    }
  ];
  

    // const useres: DataType[] = [
  //   {
  //     id: 29,
  //     email: "george.bluth@reqres.in",
  //     first_name: "George",
  //     last_name: "Bluth",
  //     job: 'Programmer',
  //     avatar: "https://reqres.in/img/faces/1-image.jpg",
  //   },
  //   {
  //     id: 32,
  //     email: "janet.weaver@reqres.in",
  //     first_name: "Janet",
  //     last_name: "Weaver",
  //     job: 'Doctor',
  //     avatar: "https://reqres.in/img/faces/2-image.jpg",
  //   },
  //   {
  //     id: 23,
  //     email: "emma.wong@reqres.in",
  //     first_name: "Emma",
  //     last_name: "Wong",
  //     job: 'Manager',
  //     avatar: "https://reqres.in/img/faces/3-image.jpg",
  //   },
  //   {
  //     id: 49,
  //     email: "eve.holt@reqres.in",
  //     first_name: "Eve",
  //     last_name: "Holt",
  //     job: 'Engineer',
  //     avatar: "https://reqres.in/img/faces/4-image.jpg",
  //   },
  //   {
  //     id: 38,
  //     email: "charles.morris@reqres.in",
  //     first_name: "Charles",
  //     last_name: "Morris",
  //     job: 'Engineer',
  //     avatar: "https://reqres.in/img/faces/5-image.jpg",
  //   },
  //   {
  //     id: 36,
  //     email: "tracey.ramos@reqres.in",
  //     first_name: "Tracey",
  //     last_name: "Ramos",
  //     job: 'Programmer',
  //     avatar: "https://reqres.in/img/faces/6-image.jpg",
  //   },
  //   {
  //     id: 32,
  //     email: "michael.lawson@reqres.in",
  //     first_name: "Michael",
  //     last_name: "Lawson",
  //     job: 'Doctor',
  //     avatar: "https://reqres.in/img/faces/7-image.jpg",
  //   },
  //   {
  //     id: 28,
  //     email: "lindsay.ferguson@reqres.in",
  //     first_name: "Lindsay",
  //     last_name: "Ferguson",
  //     job: 'Programmer',
  //     avatar: "https://reqres.in/img/faces/8-image.jpg",
  //   },
  //   {
  //     id: 30,
  //     email: "tobias.funke@reqres.in",
  //     first_name: "Tobias",
  //     last_name: "Funke",
  //     job: 'Teacher',
  //     avatar: "https://reqres.in/img/faces/9-image.jpg",
  //   },
  //   {
  //     id: 33,
  //     email: "byron.fields@reqres.in",
  //     first_name: "Byron",
  //     last_name: "Fields",
  //     job: 'Engineer',
  //     avatar: "https://reqres.in/img/faces/10-image.jpg",
  //   },
  //   {
  //     id: 29,
  //     email: "george.edwards@reqres.in",
  //     first_name: "George",
  //     last_name: "Edwards",
  //     job: 'Teacher',
  //     avatar: "https://reqres.in/img/faces/11-image.jpg",
  //   },
  //   {
  //     id: 35,
  //     email: "rachel.howell@reqres.in",
  //     first_name: "Rachel",
  //     last_name: "Howell",
  //     job: 'Doctor',
  //     avatar: "https://reqres.in/img/faces/12-image.jpg",
  //   }
  // ];